services:
  web:
   image: nginx:latest
   ports:
    - 8080:80
   volumes:
    - ./backend:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   networks:
    - backend-network

  frontend:
    build: 
      context: './frontend'
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - backend-network
      
  php:
    build:
      context: './backend/Docker'
    container_name: php-container
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  db-data:

