services:
  web:
   image: nginx:latest
   ports:
    - 8080:80
   volumes:
    - ./backend:/var/www/html
    - ./nginx-backend/default.conf:/etc/nginx/conf.d/default.conf
   networks:
    - backend-network

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-container
    ports: 
      - 3000:80
    networks:
      - backend-network
      - frontend-network
    volumes:
      - ./frontend/nginx-frontend/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: './backend/Docker'
    container_name: php-container
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  db-data:

